### ISSUE TITLE
Notice when BuddyPress is inactive

### ISSUE THREAD

**Issue by 1naveengiri** [sbrajesh/bp-live-notification#4]
When For some reason BuddyPress is Inactive so as a Plus point, the BuddyPress intended plugin should give Admin Notice for BuddyPress requirement.

**Comment by 1naveengiri** [comment]
<script src="https://gist.github.com/1naveengiri/675d4acbcc8aa47f42fd2ca0a923ce72.js"></script>

**Comment by 1naveengiri** [comment]
https://gist.github.com/1naveengiri/675d4acbcc8aa47f42fd2ca0a923ce72

**Comment by sbrajesh** [comment]
Thank you Naveen.
I don't think it will do any good to add a notification. The important things is the plugin should not break the install if BuddyPress is not active.
On a normal BuddyPress install, I have seen clients using around 25-20 plugins on average, if each plugin started adding notice, the admin panel will be over flooded.

I appreciate your suggestion but it does not merit to be included in the plugin.
